### ISSUE TITLE
Question: Does the daemon need to run continuosly?

### ISSUE THREAD

**Issue by amoghgarg1990** [kubernetes-incubator/ip-masq-agent#29]
If my cluster's POD CIDR does not change during the lifetime of the node, do I need to run this masq agent continuously?

As in, if I manually (or using shell scripts) configure the relevant IPTable Masquerading rules, will that serve the purpose of this ip-masq-agent? 

Basically if the `/etc/config/ip-masq-agent` file in my node never changes, does ip-masq-agent need to be a daemon or can it just be a job that runs once when the node starts for the first time.

Or is my understanding of this agent flawed?

**Comment by MrHohn** [comment]
> If my cluster's POD CIDR does not change during the lifetime of the node, do I need to run this masq agent continuously?

No if there is no need for dynamically configuring the non-masquerade ranges. Though having this run continuously may help for re-ensuring in case the rules get messed up.

> As in, if I manually (or using shell scripts) configure the relevant IPTable Masquerading rules, will that serve the purpose of this ip-masq-agent?

Yep that serves the same purpose.

> Basically if the /etc/config/ip-masq-agent file in my node never changes, does ip-masq-agent need to be a daemon or can it just be a job that runs once when the node starts for the first time.

Totally, in fact, that is exactly how GCE kube-up script does today: https://github.com/kubernetes/kubernetes/blob/a213886f9cd37ea9bc4c7b2fdbdb872f86880570/cluster/gce/gci/configure-helper.sh#L96-L105

**Comment by amoghgarg1990** [comment]
@MrHohn Thanks for the reply!
