### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by aojea** [kubernetes-incubator/ip-masq-agent#43]
Current ip-masq-agent doesn't work for ipv6 clusters, I think that's because it's hardcoded to work with ipv4 per the line below:

https://github.com/kubernetes-incubator/ip-masq-agent/blob/c4df3bcd4ebbffb201893818624e784c7343dad1/cmd/ip-masq-agent/ip-masq-agent.go#L111

What would be the best way to have ipv6 support, make this protocol parameter configurable, run one daemon per protocol (ipv4 and/or ipv6), create a new ipv6-masq-agent, ...?

/cc @BenTheElder

**Comment by BenTheElder** [comment]
cc @MrHohn for thoughts

**Comment by MrHohn** [comment]
Given dual-stack isn't yet support on k8s, I would suggest simply making protocol param configurable for now (like what kube-proxy currently does).

cc @varunmar @grayluck

**Comment by aramase** [comment]
PR to support IPv6 has been merged - https://github.com/kubernetes-incubator/ip-masq-agent/pull/45

@aojea can we close this issue?

**Comment by aojea** [comment]
absolutely, thank you very much
