### ISSUE TITLE
New release of ip-masq-agent with ipv6 support

### ISSUE THREAD

**Issue by aramase** [kubernetes-incubator/ip-masq-agent#47]
#45 added ipv6 support to ip-masq-agent.
We need to create a new release with this feature included.

/assign @bowei @varunmar 

cc @khenidak

**Comment by aramase** [comment]
cc @varunmar

**Comment by aramase** [comment]
ping @bowei @varunmar

**Comment by lachie83** [comment]
👋 1.16 release lead here. Some new dual-stack features in Kubernetes have just landed in 1.16 and we would like to get a new release published before 1.16 goes out. Can we get a status update on when the new release image will be available?

**Comment by MrHohn** [comment]
@lachie83 We are in the process of publishing the new images. Should be available soon after the long weekend.

**Comment by lachie83** [comment]
Thank you very much @MrHohn

**Comment by MrHohn** [comment]
New images had been published :)
https://github.com/kubernetes-incubator/ip-masq-agent/releases/tag/v2.5.0

**Comment by aramase** [comment]
Thank you @MrHohn!

**Comment by lachie83** [comment]
Thank you!
